#!/usr/bin/env python3

from requests import Session
from requests.auth import HTTPDigestAuth

api_root = f"http://192.168.1.64/ISAPI"

session = Session()
session.auth = HTTPDigestAuth("admin", "asdf1234")


def to_xml(x):
    if isinstance(x, dict):
        return "".join(f"<{k}>{to_xml(v)}</{k}>"for k, v in x.items())
    else:
        return str(x)


def put(url, data):
    data = to_xml(data)
    print(f"PUT {url} {data}")
    r = session.put(f"{api_root}/{url}", data)
    assert r.status_code in [200], (r.status_code, r.text)


def configure_camera():
    put("Streaming/channels/101", {"StreamingChannel": {"Video": {
        "videoCodecType": "H.265",
        "videoResolutionWidth": 1920,
        "videoResolutionHeight": 1080,
        "videoQualityControlType": "vbr",
        "fixedQuality": 60,  # Medium
        "maxFrameRate": 2500,
        # H.26X+
        "SmartCodec": {"enabled": "true"},
        "vbrUpperCap": 4096,
        "vbrAverageCap": 2048,
        "smoothing": 50,
    }}})
    put("Image/channels/1/WDR", {"WDR": {"mode": "open", "WDRLevel": 50}})
    put("Image/channels/1/sharpness", {"Sharpness": {"SharpnessLevel": 25}})
    put("Image/channels/1/color", {"Color": {
        "brightnessLevel": 50,
        "contrastLevel": 25,
        "saturationLevel": 50,
    }})
    put("Image/channels/1/shutter", {"Shutter": {
        "ShutterLevel": "1/25",
        "maxShutterLevelLimit": "1/100",
    }})
    # Disable Wireless Hotspot, maybe consuming power
    put("System/Network/interfaces/2/wirelessServer",
        {"WirelessServer": {"wifiApEnabled": "false", "ssid": "HAP_VOVLTS"}})
    # Add image flip
    put("Image/channels/1/imageFlip",
        {"ImageFlip": {"enabled": "true", "ImageFlipStyle": "CENTER"}})


if __name__ == "__main__":
    configure_camera()
