#!/usr/bin/env bash
set -e
echo v3 | sudo -S echo &> /dev/null

# apt
# NOTE: Kernel packages must not be touched else /lib/modules/tegra*/ 
#       kernel modules will be cleared or corrupted leading to empty lsmod
sudo apt-get update
sudo apt-mark hold nvidia-l4t-kernel nvidia-l4t-display-kernel
sudo apt-get --yes dist-upgrade
sudo apt-get --yes --purge autoremove
# NOTE: apache2-utils for htpasswd
sudo apt-get --yes install docker-compose curl nano tmux git apache2-utils nmap
sudo apt-get --yes install python3-pip
# NOTE: pip3 for sudo access
sudo pip3 install pyserial epevermodbus

# Setup Docker post-installation
docker image ls 2> /dev/null || (
    sudo usermod -aG docker v3
    newgrp docker
    echo v3 | sudo -S echo &> /dev/null
)

sudo python3 << EOF
import json
json_path = "/etc/docker/daemon.json"
with open(json_path) as f:
    x = json.load(f)
x["default-runtime"] = "nvidia"
x = json.dumps(x, indent=2)
with open(json_path, "w") as f:
    f.write(x)
EOF
sudo -S systemctl restart docker

sudo nmcli c m "Wired connection 2" ipv4.address 192.168.1.123/24
sudo nmcli c m "Wired connection 2" ipv4.method manual
sudo nmcli c up "Wired connection 2"

sudo nmcli c | grep gsm > /dev/null || (
    sudo nmcli c add type gsm apn e-ideas
    sudo nmcli c up gsm
)

# sudo nvpmodel --mode 1

# sudo mmcli -m 0 --location-enable-gps-nmea
# sudo mmcli -m 0 --location-get

# UUID=8A56-306C /mnt/usb exfat defaults,nofail,x-systemd.device-timeout=3 0 2