#!/usr/bin/env python3

import subprocess
from time import sleep
from os.path import exists
import re


def has_modem():
    pipe = subprocess.run(["mmcli", "-L"], capture_output=True)
    return "no modem" not in pipe.stdout.decode().lower()


def has_usb(vendor_id, product_id):
    pipe = subprocess.run(["lsusb"], capture_output=True)
    lsusb = re.findall(r"[0-9a-f]{4}:[0-9a-f]{4}", pipe.stdout.decode())
    return f"{vendor_id}:{product_id}" in lsusb


def main():
    # for CLM920 JC5 to work as USB serial modem
    # NOTE: Loop may be needed in case HW resets itself for no reason
    if has_modem():
        print("Modem exists")
        return

    vendor_id, product_id = "1286", "4e3c"
    if has_usb(vendor_id, product_id):
        print("Enabling option kernel module")
        subprocess.run(["modprobe", "option"])
        new_id_path = "/sys/bus/usb-serial/drivers/option1/new_id"
        assert exists(new_id_path), f"{new_id_path} not exists"
        with open(new_id_path, "w") as f:
            f.write(f"{vendor_id} {product_id}")
        print("Enabled option kernel module")
        return
    else:
        print(f"Incompatible device to enable option kernel module")


if __name__ == "__main__":
    main()
