#!/usr/bin/env python3

import subprocess
from time import sleep


def main():
    num_attempt = 10
    for i in range(num_attempt):
        try:
            for url in ["http://www.google.com", "203.125.7.39"]:
                cmd = ["curl", "--connect-timeout", "3", url]
                pipe = subprocess.run(cmd, capture_output=True)
                if pipe.returncode in [0]:
                    print(f"Connectivity OK: {url}")
                    return
        except Exception as e:
            print(e)
        print(f"No connection {i+1}/{num_attempt}")
        sleep(60)
    else:
        print("Rebooting")
        subprocess.run(["reboot", "now"])


if __name__ == "__main__":
    main()


# def reset_modem_and_reboot():
#     try:                                                     
#         print(f"Resetting modem")                           
#         device = serial.Serial("/dev/ttyUSB1", timeout=1)
#         device.write(b"AT&F\r")                              
#         print(device.read(1000))                                                                                         
#         print(f"Reset modem OK")
#     except Exception as e:
#         print(f"Error resetting modem: {e}")
#     sleep(3)
#     print("Sleep a few seconds before reboot")
#     run("reboot now")