#!/usr/bin/env python3

from time import sleep
from datetime import datetime

def main():
    while True:
        try:
            with open("/dev/watchdog", "w") as f:
                f.write("\0")
            print(f"Written to watchdog: {datetime.now()}")
        except Exception as e:
            print(e)
        sleep(30)

if __name__ == "__main__":
    main()
